apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: springonsk8s
spec:
  secretName: springonsk8s-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - timmhirsens-springonsk8s.67.207.72.83.nip.io
  acme:
    config:
    - domains:
      - timmhirsens-springonsk8s.67.207.72.83.nip.io
      http01:
        ingressClass: nginx